#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : perl-Time-Duration-Parse
Version  : 0.14
Release  : 1
URL      : https://cpan.metacpan.org/authors/id/N/NE/NEILB/Time-Duration-Parse-0.14.tar.gz
Source0  : https://cpan.metacpan.org/authors/id/N/NE/NEILB/Time-Duration-Parse-0.14.tar.gz
Source1  : http://http.debian.net/debian/pool/main/libt/libtime-duration-parse-perl/libtime-duration-parse-perl_0.13-1.debian.tar.xz
Summary  : 'Parse string that represents time duration'
Group    : Development/Tools
License  : Artistic-1.0-Perl
Requires: perl-Time-Duration-Parse-man
BuildRequires : perl(Exporter::Lite)
BuildRequires : perl(Time::Duration)

%description
This archive contains the distribution Time-Duration-Parse,
version 0.14:
Parse string that represents time duration

%package man
Summary: man components for the perl-Time-Duration-Parse package.
Group: Default

%description man
man components for the perl-Time-Duration-Parse package.


%prep
tar -xf %{SOURCE1}
cd ..
%setup -q -n Time-Duration-Parse-0.14
mkdir -p %{_topdir}/BUILD/Time-Duration-Parse-0.14/deblicense/
mv %{_topdir}/BUILD/debian/* %{_topdir}/BUILD/Time-Duration-Parse-0.14/deblicense/

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
if test -f Makefile.PL; then
%{__perl} Makefile.PL
make  %{?_smp_mflags}
else
%{__perl} Build.PL
./Build
fi

%check
export LANG=C
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
make TEST_VERBOSE=1 test

%install
rm -rf %{buildroot}
if test -f Makefile.PL; then
make pure_install PERL_INSTALL_ROOT=%{buildroot}
else
./Build install --installdirs=site --destdir=%{buildroot}
fi
find %{buildroot} -type f -name .packlist -exec rm -f {} ';'
find %{buildroot} -depth -type d -exec rmdir {} 2>/dev/null ';'
find %{buildroot} -type f -name '*.bs' -empty -exec rm -f {} ';'
%{_fixperms} %{buildroot}/*

%files
%defattr(-,root,root,-)
/usr/lib/perl5/site_perl/5.26.1/Time/Duration/Parse.pm

%files man
%defattr(-,root,root,-)
/usr/share/man/man3/Time::Duration::Parse.3
