#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : perl-Time-Duration-Parse
Version  : 0.16
Release  : 25
URL      : https://cpan.metacpan.org/authors/id/N/NE/NEILB/Time-Duration-Parse-0.16.tar.gz
Source0  : https://cpan.metacpan.org/authors/id/N/NE/NEILB/Time-Duration-Parse-0.16.tar.gz
Source1  : http://http.debian.net/debian/pool/main/libt/libtime-duration-parse-perl/libtime-duration-parse-perl_0.13-1.debian.tar.xz
Summary  : 'Parse string that represents time duration'
Group    : Development/Tools
License  : Artistic-1.0 Artistic-1.0-Perl GPL-1.0
Requires: perl-Time-Duration-Parse-license = %{version}-%{release}
Requires: perl-Time-Duration-Parse-perl = %{version}-%{release}
BuildRequires : buildreq-cpan
BuildRequires : perl(Time::Duration)

%description
This archive contains the distribution Time-Duration-Parse,
version 0.16:
Parse string that represents time duration

%package dev
Summary: dev components for the perl-Time-Duration-Parse package.
Group: Development
Provides: perl-Time-Duration-Parse-devel = %{version}-%{release}
Requires: perl-Time-Duration-Parse = %{version}-%{release}

%description dev
dev components for the perl-Time-Duration-Parse package.


%package license
Summary: license components for the perl-Time-Duration-Parse package.
Group: Default

%description license
license components for the perl-Time-Duration-Parse package.


%package perl
Summary: perl components for the perl-Time-Duration-Parse package.
Group: Default
Requires: perl-Time-Duration-Parse = %{version}-%{release}

%description perl
perl components for the perl-Time-Duration-Parse package.


%prep
%setup -q -n Time-Duration-Parse-0.16
cd %{_builddir}
tar xf %{_sourcedir}/libtime-duration-parse-perl_0.13-1.debian.tar.xz
cd %{_builddir}/Time-Duration-Parse-0.16
mkdir -p deblicense/
cp -r %{_builddir}/debian/* %{_builddir}/Time-Duration-Parse-0.16/deblicense/

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
if test -f Makefile.PL; then
%{__perl} Makefile.PL
make  %{?_smp_mflags}
else
%{__perl} Build.PL
./Build
fi

%check
export LANG=C.UTF-8
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
make TEST_VERBOSE=1 test

%install
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/perl-Time-Duration-Parse
cp %{_builddir}/Time-Duration-Parse-0.16/LICENSE %{buildroot}/usr/share/package-licenses/perl-Time-Duration-Parse/0c5dcebf0a8f9accc5e008188fed6ea6d3eddafc
if test -f Makefile.PL; then
make pure_install PERL_INSTALL_ROOT=%{buildroot} INSTALLDIRS=vendor
else
./Build install --installdirs=vendor --destdir=%{buildroot}
fi
find %{buildroot} -type f -name .packlist -exec rm -f {} ';'
find %{buildroot} -depth -type d -exec rmdir {} 2>/dev/null ';'
find %{buildroot} -type f -name '*.bs' -empty -exec rm -f {} ';'
%{_fixperms} %{buildroot}/*

%files
%defattr(-,root,root,-)

%files dev
%defattr(-,root,root,-)
/usr/share/man/man3/Time::Duration::Parse.3

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/perl-Time-Duration-Parse/0c5dcebf0a8f9accc5e008188fed6ea6d3eddafc

%files perl
%defattr(-,root,root,-)
/usr/lib/perl5/*
